# Generated by Django 4.1.7 on 2023-02-23 16:17

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('desc', models.TextField(max_length=500)),
                ('contact_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.TextField(max_length=300)),
                ('item_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('place_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('place_location', models.CharField(max_length=100)),
                ('trending_item', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField()),
                ('item_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('user_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='place_foreign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
        migrations.CreateModel(
            name='GuideDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('desc', models.TextField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=200)),
                ('place_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
                ('user_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=100)),
                ('guide_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('guide_description', models.TextField(max_length=200)),
                ('place_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(max_length=100)),
                ('festival_desc', models.TextField(max_length=300)),
                ('festival_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('place_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.URLField()),
                ('attact_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attraction')),
                ('place_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
                ('user_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attraction',
            name='place_foreign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('activity_description', models.TextField(max_length=1000)),
                ('place_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
            ],
        ),
    ]
